name: remixicon
description: Remix icon is a set of open-source neutral-style system symbols elaborately crafted for designers and developers.
version: 1.0.0
homepage: https://github.com/alialnaghmoush/remixicon

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Remix
      fonts:
        - asset: fonts/Remix.ttf
